name: Deploy frontend staging

on:
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: testReact-staging
  AZURE_WEBAPP_PACKAGE_PATH: "React/calculator-master"

# defaults:
#   run:
#     working-directory: ./React/calculator-master

jobs:
  build-and-deploy:
    name: Build and deploy frontend
    runs-on: ubuntu-latest
    environment:
      name: "Development-new"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2

      - name: Get NodeJS Version from package.json
        run: |
          echo "$(cat ./React/calculator-master/package.json)" | jq .engines.node | xargs -I {} echo "NodeVersion="{} >> $GITHUB_ENV

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{env.NodeVersion}}
          cache: "npm"
          cache-dependency-path: React/calculator-master/package.json

      - name: Install dependencies
        working-directory: React/calculator-master
        run: npm ci

      - name: Build
        working-directory: React/calculator-master
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_FTAPP_STAGING_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
